name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme-en:
    name: WakaReadme English
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          README_FILE: README.md

  update-readme-ja:
    name: WakaReadme Japanese
    needs: update-readme-en
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          README_FILE: README.ja.md

  update-readme-zh:
    name: WakaReadme Chinese
    needs: update-readme-ja
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          README_FILE: README.zh.md
